import Head from "next/head"

export default function About() {
    return (
        <>
            <Head>
                <title>ประวัติความเป็นมา - Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="pb-5 pt-[1rem]">
                <div className="container mx-auto border bg-white p-4 rounded-lg overflow-hidden">
                    <h1 className="title text-3xl">ประวัติความเป็นมา</h1>

                    <hr className="my-2" />

                    <div className="structure h-full my-10">
                        <div className="container">
                            
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
