import Head from "next/head"

export default function Executives() {
    return (
        <>
            <Head>
                <title>ผู้บริหารหน่วยงาน - Executives</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="pb-5 pt-[1rem] xl:px-4">
                <div className="container mx-auto border bg-white p-4 rounded-lg overflow-hidden">
                    <h1 className="title text-3xl">ผู้บริหารหน่วยงาน</h1>

                    <hr className="my-2" />

                    <div className="vision h-full my-10">
                        
                    </div>
                </div>
            </section>
        </>
    )
}
