import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import PostList from '../components/posts/post-list'
import SlideHeros from '../components/heros/slide-heros'
import VideoList from '../components/videos/video-list'
import dynamic from "next/dynamic"
import OptionMenu from '../components/option-menu/OptionMenu'

const inter = Inter({ subsets: ['latin'] })
const Map = dynamic(() => import('../components/maps/map-area'), {
    ssr: false
})

export default function Home() {
    return (
        <>
            <Head>
                <title>หน้าหลัก - Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Section 1 */}
            <SlideHeros />

            {/* Section 2 */}
            <OptionMenu />

            {/* Posts Section */}
            <PostList />

            {/* Videos Section */}
            <VideoList />

            {/* Map Section */}
            <Map />

            {/* Bottom Section */}
            <div className="bg-white flex items-center justify-center" style={{ height: '150px' }}>
                Bottom
            </div>
        </>
    )
}
