import Head from "next/head"

export default function Structure() {
    return (
        <>
            <Head>
                <title>โครงสร้างองค์กร - Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="p-2">
                <h1 className="title text-3xl">โครงสร้างองค์กร</h1>

                <div className="structure h-full my-10">
                    <div className="container">
                        <h1 className="level-1 rectangle">CEO</h1>
                        <ol className="level-2-wrapper">
                            <li>
                                <h2 className="level-2 rectangle">Director A</h2>
                                <ol className="level-3-wrapper">
                                    <li>
                                        <h3 className="level-3 rectangle">Manager A</h3>
                                        <ol className="level-4-wrapper">
                                            <li><h4 className="level-4 rectangle">Person A</h4></li>
                                            <li><h4 className="level-4 rectangle">Person B</h4></li>
                                            <li><h4 className="level-4 rectangle">Person C</h4></li>
                                            <li><h4 className="level-4 rectangle">Person D</h4></li>
                                        </ol>
                                    </li>
                                    <li>
                                        <h3 className="level-3 rectangle">Manager B</h3>
                                        <ol className="level-4-wrapper">
                                            <li><h4 className="level-4 rectangle">Person A</h4></li>
                                            <li><h4 className="level-4 rectangle">Person B</h4></li>
                                            <li><h4 className="level-4 rectangle">Person C</h4></li>
                                            <li><h4 className="level-4 rectangle">Person D</h4></li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <h2 className="level-2 rectangle">Director B</h2>
                                <ol className="level-3-wrapper">
                                    <li>
                                    <h3 className="level-3 rectangle">Manager C</h3>
                                    <ol className="level-4-wrapper">
                                        <li>
                                        <h4 className="level-4 rectangle">Person A</h4>
                                        </li>
                                        <li>
                                        <h4 className="level-4 rectangle">Person B</h4>
                                        </li>
                                        <li>
                                        <h4 className="level-4 rectangle">Person C</h4>
                                        </li>
                                        <li>
                                        <h4 className="level-4 rectangle">Person D</h4>
                                        </li>
                                    </ol>
                                    </li>
                                    <li>
                                    <h3 className="level-3 rectangle">Manager D</h3>
                                    <ol className="level-4-wrapper">
                                        <li>
                                        <h4 className="level-4 rectangle">Person A</h4>
                                        </li>
                                        <li>
                                        <h4 className="level-4 rectangle">Person B</h4>
                                        </li>
                                        <li>
                                        <h4 className="level-4 rectangle">Person C</h4>
                                        </li>
                                        <li>
                                        <h4 className="level-4 rectangle">Person D</h4>
                                        </li>
                                    </ol>
                                    </li>
                                </ol>
                            </li>
                        </ol>
                    </div>
                </div>
            </section>
        </>
    )
}
