import Head from "next/head"

export default function Vision() {
    return (
        <>
            <Head>
                <title>วิสัยทัศน์/พันธกิจ/ค่านิยม - Vision / Mission / Core Values</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="pb-5 pt-[1rem] xl:px-4">
                <div className="container mx-auto border bg-white p-4 rounded-lg overflow-hidden">
                    <h1 className="title text-3xl">วิสัยทัศน์/พันธกิจ/ค่านิยม</h1>

                    <hr className="my-2" />

                    <div className="vision h-full mb-10">
                        <div className="mt-5 flex flex-col px-10">
                            <h3 className="text-2xl font-bold">วิสัยทัศน์</h3>
                            <blockquote className="vision-quote text-center">
                                <p className="text-2xl font-bold">เป็นองค์กรหลักด้านการส่งเสริมสุขภาพจิตและป้องกันปัญหาสุขภาพจิตระดับเขตสุขภาพ<br /> เพื่อประชาชนสุขภาพจิตดี สู่สังคมและเศรษฐกิจมูลค่าสูง</p>
                            </blockquote>
                        </div>
                        
                        <div className="mt-[50px] flex flex-col bg-gray-100 py-4 px-10">
                            <h3 className="text-2xl font-bold">พันธกิจ</h3>
                            <div className="my-4 mx-16 max-sm:mx-0 flex justify-center items-center">
                                <ol className="gradient-list w-3/4 sm:w-full">
                                    <li>ศึกษา วิเคราะห์ วิจัยและพัฒนาองค์ความรู้ด้านการส่งเสริมสุขภาพจิตและป้องกันปัญหาสุขภาพจิตในเขตพื้นที่รับผิดชอบ</li>
                                    <li>พัฒนาศักยภาพเครือข่ายในเขตพื้นที่รับผิดชอบ โดยการถ่ายทอดองค์ความรู้และเทคโนโลยีด้านสุขภาพจิต</li>
                                    <li>เฝ้าระวังและวางแผนการส่งเสริม ป้องกัน และแก้ไขปัญหาสุขภาพจิตในเขตพื้นที่รับผิดชอบด้วยข้อมูลสารสนเทศด้านสุขภาพจิตที่มีคุณภาพ</li>
                                    <li>นิเทศและติดตามผลการปฏิบัติงานด้านสุขภาพจิตของเคือข่ายในเขตพื้นที่รับผิดชอบ</li>
                                </ol>
                            </div>
                        </div>

                        <div className="mt-[50px] flex flex-col px-10">
                            <h3 className="text-2xl font-bold">ค่านิยม</h3>
                            <blockquote className="core__value-quote text-center">
                                <p className="text-xl font-bold">
                                    หัวใจบริการ
                                    มุ่งงานคุณภาพ
                                    ทำงานเป็นทีม
                                    โปร่งใสตรวจสอบได้
                                </p>
                            </blockquote>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
