import Head from "next/head"

export default function Vision() {
    return (
        <>
            <Head>
                <title>วิสัยทัศน์/พันธกิจ - Vision / Mission</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="pb-5 pt-[1rem] xl:px-4">
                <div className="container mx-auto border bg-white p-4 rounded-lg overflow-hidden">
                    <h1 className="title text-3xl">วิสัยทัศน์/พันธกิจ</h1>

                    <hr className="my-2" />

                    <div className="vision h-full mb-10 px-10">
                        <div className="mt-5 flex flex-col">
                            <h3 className="text-2xl">วิสัยทัศน์</h3>
                            <blockquote className="text-center">
                                <p className="text-xl font-bold">เป็นองค์กรหลักด้านการส่งเสริมสุขภาพจิตและป้องกันปัญหาสุขภาพจิตระดับเขตสุขภาพ<br /> เพื่อประชาชนสุขภาพจิตดี สู่สังคมและเศรษฐกิจมูลค่าสูง</p>
                            </blockquote>
                        </div>
                        
                        <div className="mt-[50px] flex flex-col">
                            <h3 className="text-2xl">พันธกิจ</h3>
                            <ul className="border ml-10 flex flex-col gap-2">
                                <li>ศึกษา วิเคราะห์ วิจัยและพัฒนาองค์ความรู้ด้านการส่งเสริมสุขภาพจิตและป้องกันปัญหาสุขภาพจิตในเขตพื้นที่รับผิดชอบ</li>
                                <li>พัฒนาศักยภาพเครือข่ายในเขตพื้นที่รับผิดชอบ โดยการถ่ายทอดองค์ความรู้และเทคโนโลยีด้านสุขภาพจิต</li>
                                <li>เฝ้าระวังและวางแผนการส่งเสริม ป้องกัน และแก้ไขปัญหาสุขภาพจิตในเขตพื้นที่รับผิดชอบด้วยข้อมูลสารสนเทศด้านสุขภาพจิตที่มีคุณภาพ</li>
                                <li>นิเทศและติดตามผลการปฏิบัติงานด้านสุขภาพจิตของเคือข่ายในเขตพื้นที่รับผิดชอบ</li>
                            </ul>
                        </div>

                        <div className="mt-[50px] flex flex-col">
                            <h3 className="text-2xl">ค่านิยม</h3>
                            <blockquote className="text-center">
                                <p className="text-xl font-bold">
                                    หัวใจบริการ
                                    มุ่งงานคุณภาพ
                                    ทำงานเป็นทีม
                                    โปร่งใสตรวจสอบได้
                                </p>
                            </blockquote>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
